[options]
addons_path = /Users/serhanagan/Developer/Odoo Core/odoo/addons,/Users/serhanagan/Library/Application Support/Odoo/addons/17.0,/Users/serhanagan/Developer/Odoo Core/addons,/Users/serhanagan/Developer/OmniFlow
admin_passwd = admin
db_host = False
db_port = False
db_user = serhanagan
db_password = False
xmlrpc_port = 8069
db_name = omniflow_db
list_db = True
